### ISSUE TITLE
Resources for EthCC

### ISSUE THREAD

**Issue by lightclient** [quilt/reading#1]
As discussed in our standup, I've started a list of resources that will be beneficial to read before EthCC. Please share any other things that you all think is relevant.

* [Cross-chain Deals and Adversarial Commerce](https://arxiv.org/abs/1905.09743)
* [Automated Detection of Dynamic State Access in Solidity](https://ethresear.ch/t/automated-detection-of-dynamic-state-access-in-solidity/7003)
* [Cross-contract state](https://notes.ethereum.org/SCxJs3mISOG0zRDKD_hXxw)
* [A protocol for ETH transfers, even more simpler and with error-handling](https://notes.ethereum.org/Sd3pOEwrQSaYeXHdAmIEvw)
* [Atomic cross-shard via Lamport timestamps](https://notes.ethereum.org/lOGzEL0YSD6R9F_IkZMsrQ)
* [Demystifying Incentives in the Consensus Computer](https://eprint.iacr.org/2015/702.pdf)
* [The Data Availability Problem under Stateless Ethereum](https://ethresear.ch/t/the-data-availability-problem-under-stateless-ethereum/6973)
* [Combining GHOST and Casper](https://github.com/ethereum/research/blob/master/papers/ffg%2Bghost/paper.pdf)

eth 1.x updates (in order):
* https://blog.ethereum.org/2019/12/10/eth1x-files-fast-sync/
* https://blog.ethereum.org/2019/12/20/eth1x-files-digest-no-1/
* https://blog.ethereum.org/2019/12/30/eth1x-files-state-of-stateless-ethereum/
* https://blog.ethereum.org/2020/01/17/eth1x-files-digest-no-2/
* https://blog.ethereum.org/2020/01/28/eth1x-files-the-stateless-ethereum-tech-tree/
* https://blog.ethereum.org/2020/02/18/eth1x-files-the-statelessness-of-the-union/

That's what's I can think of off the top of my head. I'll also add more as they come up.

My initial feeling is to break out discussions on specific resources into new issues, that way they can be linked into the main README. I think it might be sad to only discuss them offline and let that communication be lost to the ether.

**Comment by lightclient** [comment]
Also might be good to read the phase 2 PR: https://github.com/ethereum/eth2.0-specs/pull/1628

**Comment by SamWilsn** [comment]
More eth1x-files: https://blog.ethereum.org/2020/02/28/eth1x-files-digest-no-3/
